# -*- coding: utf-8 -*-
"""Código - Trabalho Estruturas de Dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKdMooe1_JN62i261xP4yJIMs63q617X
"""

#Ana Clara Setulim Silva - 14756416
#Arthur De Oliveira Silva - 15493972
#Iara Berto Pena - 13817457
#Natália Alves Coutinho - 15675050
#Sofia Lopes Munaro - 15497823

#1ª ETAPA: importando biblioetecas
import numpy as np

#2ª ETAPA: funções utilizadas

#Dijkstra: algoritmo conhecido que calcula a menor distancia entre vértices de um grafo
def dijkstra(G, origem):
    n = len(G)
    dist = [float('inf')] * n
    dist[origem] = 0
    visitado = [False] * n

    for _ in range(n):
        u = -1
        min_dist = float('inf')
        for i in range(n):
            if not visitado[i] and dist[i] < min_dist:
                min_dist = dist[i]
                u = i
        if u == -1:
            break
        visitado[u] = True

        for v in range(n):
            if G[u][v] != float('inf') and not visitado[v]:
                if dist[u] + G[u][v] < dist[v]:
                    dist[v] = dist[u] + G[u][v]
    return dist

#Função que substitui os zeros fora da diagonal por float('inf')
#Esse passo é necessário para que o algoritmo interprete 0 como "sem conexão direta", em vez de "distância 0"
def ajustar_matriz(matriz):
    n = len(matriz)
    for i in range(n):
        for j in range(n):
            if i != j and matriz[i][j] == 0:
                matriz[i][j] = float('inf')
    return matriz

#Função que aplica o algoritmo de dijkstra ao problema
def caminhos_mais_curtos(matriz, n_focos, n_brigadas):
    n = n_focos + n_brigadas
    matriz = ajustar_matriz(matriz.copy())

    indices_focos = list(range(n_focos))
    indices_brigadas = list(range(n_focos, n))

    resultado_matriz = np.zeros((n_focos, n_brigadas))

    for j, b in enumerate(indices_brigadas):
        dist = dijkstra(matriz, b)
        for i, f in enumerate(indices_focos):
            resultado_matriz[i][j] = dist[f]

    return resultado_matriz

#3ª ETAPA:recebendo os inputs

#Número de focos de Incêndio e número de postos de brigadistas
num_focos, num_brigadas = map(int,input().split())

#Capacidade de combate ao fogo de cada posto brigadista por hora (armazenados como float numa matriz)
capacidades = list(map(float, input().split()))
capacidades = np.array([capacidades])

#Área inicial de cada foco de incêndio (armazenadas como float numa matriz)
areas = list(map(float, input().split()))
areas = np.array(areas)

#Taxa de crescimento diária aplicada ao final do dia (armazenadas como float numa matriz)
taxas_crescimento = list(map(float, input().split()))
taxas_crescimento = np.array(taxas_crescimento)
#matriz de distâncias entre os nós do grafo (focos e depois brigadas)
linhas = []
for i in range(num_focos+num_brigadas):
    elementos = list(map(int, input().strip().split()))
    linhas.append(elementos)
matriz_distancias = np.array(linhas, dtype=float) #o tipo float é necessário para implementar os passos seguintes

#4ª ETAPA: obtendo a matriz que contém o tempo mais curto possível entre as brigadas e os focos
#as linhas representam f1,f2,...,fn e as colunas b1,b2,...bm
matriz_menores_tempos = caminhos_mais_curtos(matriz_distancias,num_focos,num_brigadas)

#5ª ETAPA: cálculo do tempo útil de cada brigada para cada foco
# tempo_util_ij = 12 -  tempo_mais_curto_ij ou 0, quando o tempo para ir e voltar ultrapassa 12h
tempo_util = np.maximum(0, 12 - matriz_menores_tempos)

#6ª ETAPA: obter matriz objetivo (o objetivo é zerar todas as áreas)
#ela servirá para comparar com a matriz de áreas atuais
objetivo = np.zeros(num_focos)

#Vetor com o dia em que cada incendio foi apagado
incendios_apagados_dia = np.zeros(num_focos)

#Tempo, em dias, que foi necessário para apagar todos os incêndios
tempo_total = 0

#INÍCIO DO ALGORITMO DE ALOCAÇÃO:

for dia in range(1,101):

    #1° PASSO: cálculo da demanda diária dos focos
    #demanda_i = area_i x (taxa_i - 1) representando o quanto cada foco crescerá no dia seguinte
    #Levar isso em conta permite priorizar os focos com maior tendência a sair do controle

    demandas = areas * (taxas_crescimento - 1)

    #2° PASSO: cálculo da capacidade real de cada brigada
    #capacidade_real_ij = tempo_util_ij * capacidade_j

    capacidade_real = tempo_util * capacidades

    #3° PASSO: distribuição proporcional da demanda
    #a ideia é, para cada foco, cada brigada contribuir proporcionalmente à sua capacidade em relação
    #a soma das capacidades reais das brigadas que podem atender aquele foco
    #(por enquanto, sem se preocupar com a capacidade máxima de cada brigada)

    #matriz em que cada elemento é a soma dos elementos de cada linha da matriz capacidade_real
    soma = np.sum(capacidade_real, axis=1).reshape(-1, 1)
    soma = np.where(soma==0,1,soma) #evitar divisao por 0

    #Assim, a distribuição leva em conta tanto a demanda de cada foco quanto a capacidade das brigadas
    # distribuicao_ij = (capacidade_real_ij/soma_i) * demandas_i
    distribuicao = capacidade_real/soma * demandas.reshape(-1, 1)

    #4° PASSO: respeitar a capacidade máxima de cada brigada
    #a ideia é normalizar cada coluna da matriz distribuicao para sua soma dar 1

    soma_colunas = distribuicao.sum(axis = 0)
    soma_colunas = np.where(soma_colunas == 0, 1, soma_colunas) #evitar divisão por 0
    alocacao = distribuicao / soma_colunas

    #printar as alocações
    print('###################################################')
    print('DIA',dia)
    for b in range(num_brigadas):
        print('              ')
        for f in range(num_focos):
            if alocacao[f][b] != 0:
                print(f'Brigada {b+1} atende o foco {f+1} com {round(alocacao[f][b]*100,4)}% de sua capacidade')


    #5° PASSO: atualizar as áreas
    #descontar a quantidade apagada pelas brigadas

    #area_i = area_i - somatorio (de j=1 até n) alocacao_ij x capacidade_real_j
    areas = areas - (np.einsum('ij,ji->i',alocacao,capacidade_real.T))

    #zerar as áreas que apagaram (valores negativos)
    areas = np.where(areas<0,0,areas)

    #acrescentar a taxa de crescimento diaria
    areas = areas * taxas_crescimento

    #Verifica se algum incendio foi apagado nesse dia. Caso sim, atribui o dia em que ele foi apagado.
    for index, area in np.ndenumerate(areas):
        if area == 0 and incendios_apagados_dia[index] == 0:
            incendios_apagados_dia[index] = dia


    #6° PASSO: verificar se todos focos foram extintos
    if np.array_equal(areas,objetivo):
        tempo_total = dia
        break

if dia == 100:
    print('###################################################')
    print('Não foi possível apagar os focos')
    print('###################################################')
    print('Dia em que cada foco é extinto:')
    for i in range(len(incendios_apagados_dia)):
        if incendios_apagados_dia[i] == 0:
            print(f'Foco {i+1}: não foi possível apagar (área final: {areas[i]})')
        else:
            print(f'Foco {i+1}: {int(incendios_apagados_dia[i])}')

else:
    print('###################################################')
    print('Tempo total necessário para extinguir os focos:', tempo_total,'dias')
    print('###################################################')
    print('Dia em que cada foco é extinto:')
    for i in range(len(incendios_apagados_dia)):
        print(f'Foco {i+1}: {int(incendios_apagados_dia[i])}')

